sudo: required
language: ruby
rvm: 2.2
node_js: "0.10"
python:
  - "3.6"

jobs:
  include:
    - stage: "Test"
      before_script:
        - gem install awesome_bot
        - sudo pip install json-spec
        - sudo pip install -r requirements.txt
      script: 
        - awesome_bot contents.json -w AERecord,theswiftwebdeveloper,bluemix,swiftplayground,awesome-for-swift-cheatsheet
        - json validate --schema-file=.github/schema.json --document-file=contents.json
    - stage: "Deploy"
      script:
        - ruby .github/convert.rb
        - node .github/upgradeDb.js
        - cp README.md docs/index.md
        - mkdocs build
        # - ./.github/deploy.sh ruby .github/convert.rb && node .github/upgradeDb.js && cp README.md docs/index.md && mkdocs build
      if: branch = master AND type != pull_request

# language: python

# python:
#   - "3.6"

# script:
#   - cp README.md docs/index.md
#   - mkdocs build

# deploy:
#   provider: pages
#   local-dir: site
#   skip-cleanup: true
#   keep-history: true
#   github-token: $GITHUB_TOKEN
#   on:
#     branch: master

