site_name: Awesome Video
site_url: https://awesome.video
site_description: A curated list of awesome video frameworks, libraries and software
site_author: Nick Krzemienski
repo_name: krzemienski/awesome-video
repo_url: https://github.com/krzemienski/awesome-video
theme:
  name: material
  palette:
    primary: orange
    accent: black
extra:
  social:
    - type: github
      link: https://github.com/krzemienski
    - type: twitter
      link: https://twitter.com/nkrzemienski
    - type: linkedin
      link: https://www.linkedin.com/in/krzemienski
google_analytics:
  - UA-154476193-1
  - auto
extra_css:
    - css/extra.css
nav:
  - "Home for all video streaming resouces.": "index.md"
